version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: resume_builder_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: resume_user
      POSTGRES_PASSWORD: resume_pass_dev
      POSTGRES_DB: resume_builder
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U resume_user -d resume_builder']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

